In [2]:
import cv2
import numpy as np

In [4]:
img = cv2.imread('./data/lena.jpg')

print('img.ndim=',img.ndim) # 3차원
print('img.shape=',img.shape) # 배열 형태
print('img.dtype=',img.dtype)

img=img.astype(np.int32)
print('img.dtype=',img.dtype)

img=np.uint8(img)
print('img.dtype=',img.dtype)

img.ndim= 3
img.shape= (512, 512, 3)
img.dtype= uint8
img.dtype= int32
img.dtype= uint8


In [5]:
img=cv2.imread('./data/lena.jpg',cv2.IMREAD_GRAYSCALE)
img[100,200]=50 #100이 y좌표, 200이 x좌표 -> 좌표 변경 
print(img[100:110,200:210]) # 픽셀(밝기 값)보기 

[[ 50 145 141 139 141 142 140 139 133 139]
 [134 142 146 145 143 139 137 140 136 136]
 [128 142 146 139 136 137 139 142 135 131]
 [136 146 139 124 127 140 144 142 127 126]
 [148 139 131 134 143 146 138 128 133 142]
 [139 138 139 141 142 140 135 131 141 132]
 [147 143 139 139 141 142 141 139 133 130]
 [153 143 133 134 143 147 142 135 122 136]
 [139 136 136 139 142 141 133 126 132 135]
 [130 138 145 142 133 127 129 133 139 129]]
